apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7srs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-7srs@sha256:dfb8499ca6ae13b73aadb0867b8b9f3eb63685a9d604ba5d2c5ce0a7d1ea516c
        name: my-nodejs
        resources: {}
status: {}
